type TColor =
  | "BLACK_OPACITY"
  | "BLACK"
  | "BLUE_LIGHT"
  | "BLUE_PURPLE"
  | "BLUE_TRANSLUCID"
  | "BLUE"
  | "GLAUCOUS"
  | "GREEN_LIGHT"
  | "GREEN_TRANSLUCID"
  | "GREEN"
  | "GREY_LIGHT"
  | "GREY"
  | "LIGHT"
  | "ORANGE_LIGHT"
  | "ORANGE_TRANSLUCID"
  | "ORANGE"
  | "PURPLE_TRANSLUCID"
  | "PURPLE"
  | "RED_LIGHT"
  | "TRANSPARENT"
  | "WHITE"
  | "YELLOW_LIGHT"
  | "YELLOW";

const colors: Record<TColor, string> = {
  BLACK: "#575757",
  BLACK_OPACITY: "#5757574D",
  BLUE: "#28779B",
  BLUE_LIGHT: "#51AFF7",
  BLUE_PURPLE: "#9FA4EE",
  BLUE_TRANSLUCID: "#28779C4D",
  GLAUCOUS: "#6682D7",
  GREEN: "#28AD46",
  GREEN_LIGHT: "#6BC39E",
  GREEN_TRANSLUCID: "#28AD464D",
  GREY: "#808080",
  GREY_LIGHT: "#C0C0C0",
  LIGHT: "#EDEEFF",
  ORANGE: "#E16926",
  ORANGE_LIGHT: "#FFB186",
  ORANGE_TRANSLUCID: "#E169264D",
  PURPLE: "#9B28AD",
  PURPLE_TRANSLUCID: "#9B28AD4D",
  RED_LIGHT: "#D76682",
  TRANSPARENT: "#FFF0",
  WHITE: "#FFF",
  YELLOW: "#EE9B00",
  YELLOW_LIGHT: "#FFEFCA",
};

export { colors };
export type { TColor };
