name: front
on:
  pull_request:
    branches:
      - main
    paths:
      - packages/front/**
  workflow_dispatch:
jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/front
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Install front dependencies
        run: npm ci

  lint:
    name: Lint & Format
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/front
    steps:
      - uses: actions/checkout@v3

      - name: Lint
        run: npm run lint:check

      - name: Format
        run: npm run format:check
  test:
    name: Test
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/front
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: npm run test
