name: front
on:
  pull_request:
    branches:
      - main
    paths:
      - packages/front/**
jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/front
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Install front dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:check

      - name: Format
        run: npm run format:check
