name: front
on:
  pull_request:
    branches:
      - main
    paths:
      - front/**
jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./front
    steps:
      - uses: actions/checkout@v3

      - name: Prettier
        run: npm run format

      - name: ESLint
        run: npm run lint
